### ISSUE TITLE
What is the relation of this to RRA?

### ISSUE THREAD

**Issue by brunosan** [WorldBank-Transport/rra-datapipeline#10]
This repository is referenced on https://github.com/WorldBank-Transport/Rural-Road-Accessibility, but no how it fits, or how to use it.

**Comment by danielfdsilva** [comment]
@brunosan This repo contains the source code for the docker container we're using to generate the results.

Documentation is still lacking but there are no actions needed here. When we commit new code, the container gets automatically built and published to [docker hub](https://hub.docker.com/r/wbtransport/rra-analysis/).

When the server executes docker the first time, the container gets automatically downloaded.

**Comment by brunosan** [comment]
Thanks @danielfdsilva. I understand that there is no reason to separately install and compile this repo when running RRA locally.

Closing here, please reopen if that is not the case and one has to install this locally.
